<a href="https://colab.research.google.com/github/SutapaNayak/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Import the numpy package under the name np and Print the numpy version and the configuration

In [19]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2.Create a null vector of size 10

In [ ]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create Simple 1-D array and check type and check data types in array

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 23, 56, 100])
print(arr)
print(type(arr))
print(arr.dtype)

[  1   2   3  23  56 100]
<class 'numpy.ndarray'>
int64


4.How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
# import library
import numpy as np
  
# create a numpy 1d-array
x = np.array([100,20,34])
  
print("Size of the array: ",
      x.size)
print("Shape of the array: ",
      x.shape)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Size of the array:  3
Shape of the array:  (3,)
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


5.Create a null vector of size 10 but the fifth value which is 1

In [ ]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6.Create a vector with values ranging from 10 to 49

In [ ]:
import numpy as np
v = np.arange(10,50)
print("Original vector:")
print(v)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


7.Reverse a vector (first element becomes last

In [ ]:
import numpy as np
import numpy as np
x = np.arange(12, 20)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19]
Reverse array:
[19 18 17 16 15 14 13 12]


8.Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9.Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
import numpy as np
nums = np.array([1,2,0,0,4,0])
print("Original array:")
print(nums)
print("Indices of elements equal to zero of the said array:")
result = np.where(nums == 0)[0]
print(result)

Original array:
[1 2 0 0 4 0]
Indices of elements equal to zero of the said array:
[2 3 5]


10.Create a 3x3 identity matrix

In [20]:
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.Create a 3x3x3 array with random values

In [21]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.86928504 0.48900892 0.9311796 ]
  [0.95288289 0.76678469 0.39772253]
  [0.76321184 0.34971927 0.77607088]]

 [[0.34134523 0.23316875 0.76000861]
  [0.71676385 0.77418714 0.97572441]
  [0.27429224 0.73051385 0.8980694 ]]

 [[0.9199361  0.86148344 0.19814055]
  [0.99852819 0.9527384  0.9607163 ]
  [0.88509012 0.2384328  0.35396559]]]


12.Create a 10x10 array with random values and find the minimum and maximum values

In [22]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.45708679 0.36186276 0.1697594  0.24479522 0.49578377 0.72067417
  0.601967   0.23075587 0.61095725 0.90419353]
 [0.43303182 0.12040051 0.20810193 0.65018001 0.63312718 0.34217281
  0.03965752 0.96896525 0.18384045 0.8707922 ]
 [0.71153371 0.90821204 0.91729729 0.04072124 0.37641605 0.21204802
  0.32894297 0.67183839 0.65299032 0.64024543]
 [0.63368296 0.09655229 0.90492155 0.69895647 0.90825353 0.21390527
  0.24567759 0.78707044 0.85126761 0.04423569]
 [0.37720748 0.70006403 0.91375079 0.43095086 0.20722016 0.92636308
  0.34231357 0.6658719  0.99822086 0.62489769]
 [0.46309133 0.01452556 0.21071569 0.15268862 0.75874922 0.88658497
  0.04929418 0.04536037 0.79388795 0.52444539]
 [0.1645653  0.5534483  0.30872299 0.72440696 0.64582384 0.74773426
  0.10573626 0.30228777 0.15175545 0.91986525]
 [0.00217928 0.6378404  0.34626747 0.96596227 0.30161576 0.1079503
  0.69435623 0.05515552 0.89388737 0.36663451]
 [0.16316249 0.49525094 0.50525047 0.37478597 0.6527193  0.676464

13.Create a random vector of size 30 and find the mean value

In [27]:
import numpy as np
x = np.random.random(30)
print("Original array:")
print(x)
x_mean=x.mean()
print("Mean of the array:" , x_mean)


Original array:
[0.15766055 0.05006016 0.04913624 0.47495839 0.41708295 0.71830232
 0.64756591 0.33083382 0.93656166 0.51548281 0.23192925 0.57381883
 0.37809495 0.54986871 0.58825606 0.46798068 0.53237157 0.54487498
 0.70713282 0.28335634 0.06697301 0.03432997 0.63536462 0.49018241
 0.53785523 0.55925418 0.41579708 0.68976446 0.9359179  0.69634604]
Mean of the array: 0.4739037965993799


14.Create a 2d array with 1 on the border and 0 inside

In [28]:
import numpy as np
x = np.ones((5,6))
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


15.How to add a border (filled with 0's) around an existing array

In [30]:
import numpy as np
x = np.ones((4,4))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, 
get first row only, 
get 3rd column only, 
get [2, 4, 6], 
replace 13 by 20

In [45]:
import numpy as np
A= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)
print("Geting 13:",A[1,5])
print("getting first row only: ",A[0,:])
print('getting 3rd column only:',A[:,2])
print("getting [2, 4, 6]:",A[0,:][1:6:2])
A[1,5]=20
print("replace 13 by 20:",A)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Geting 13: 13
getting first row only:  [1 2 3 4 5 6 7]
getting 3rd column only: [ 3 10]
getting [2, 4, 6]: [2 4 6]
replace 13 by 20: [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


17.How to Convert a 1D array to a 2D array with 2 rows

In [46]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print ('Before reshaping:')
print (arr)
arr1 = arr.reshape(4, 2)
print ('After reshaping having dimension 4x2:')
print (arr1)

  

Before reshaping:
[1 2 3 4 5 6 7 8]
After reshaping having dimension 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
import numpy as np
arr=np.array([1,2,3])
print(np.r_[np.repeat(arr, 3), np.tile(arr, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


19.Write a program to show how Numpy taking less memory compared to Python List?

In [50]:
import numpy as np
import sys
l= range(1000)
print("Size of a element in list: ",sys.getsizeof(l))
print("Size of list: ",sys.getsizeof(l)*len(l))
a1= np.arange(1000)
print("Size of a elemet in array: ",a1.itemsize)
print("Size of array declared by numpy: ",a1.size*a1.itemsize)



Size of a element in list:  48
Size of list:  48000
Size of a elemet in array:  8
Size of array declared by numpy:  8000


20.Write a program to show how Numpy taking less time compared to Python List?

In [63]:
import numpy
import time
size = 1000000
l1 = range(size)
l2 = range(size)
n1 = numpy.arange(size)
n2 = numpy.arange(size)
start = time.time()
result = [(x+y) for x, y in zip(l1, l2)]
t1=((time.time() - start)*1000)
print("Time taken by Lists to perform additon:",t1)
start = time.time()
result1 = n1 + n2
t2=(time.time() - start)
print("Time taken by NumPy Arrays to perform addition:",t2)
if t1>t2:
   print("Time taken by python list is greater than numpy")
else:
   print("Time taken by python list is less than numpy")


Time taken by Lists to perform additon: 123.48079681396484
Time taken by NumPy Arrays to perform addition: 0.0022652149200439453
Time taken by python list is greater than numpy
